{{- range $key, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: microservices
  labels:
    app: microservice-demo
    component: {{ $service.name }}
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      run: {{ $service.name }}
  template:
    metadata:
      labels:
        run: {{ $service.name }}
    spec:
      containers:
      - name: {{ $service.name }}
        image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
        imagePullPolicy: {{ $service.image.pullPolicy }}
        ports:
        - containerPort: {{ $service.service.targetPort }}
        {{- with $.Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
