apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    component: apache
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    component: catalog
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    component: customer
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: microservices
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    component: order
