apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: microservices
commonLabels:
  environment: dev
replicas:
- name: apache
  count: 1
- name: catalog
  count: 1
- name: customer
  count: 1
- name: order
  count: 1
